server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: hexletProject

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  api-docs:
    path: /swagger.html